name: network_connectivity_bridge
description: >
  A singleton wrapper for connectivity_plus to avoid listener conflicts in plugins and apps.
  This ensures that both plugins and your app can listen to network status changes safely.

version: 0.1.0
homepage: https://github.com/carlcy/network_connectivity_bridge
repository: https://github.com/carlcy/network_connectivity_bridge
issue_tracker: https://github.com/carlcy/network_connectivity_bridge/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  connectivity_plus: ^6.1.4

flutter:
  plugin:
    platforms:
      android:
        package: network_connectivity_bridge
        pluginClass: NetworkConnectivityBridgePlugin
      ios:
        pluginClass: NetworkConnectivityBridgePlugin
      web:
        pluginClass: NetworkConnectivityBridgeWeb
        fileName: network_connectivity_bridge_web.dart
      macos:
        pluginClass: NetworkConnectivityBridgePlugin
      windows:
        pluginClass: NetworkConnectivityBridgePlugin
      linux:
        pluginClass: NetworkConnectivityBridgePlugin
